.PHONY: all
.all: applications
	echo "Setting up computer..."

.PHONY: brew
brew:
ifneq (, $(shell which lzop))
	@echo "Installing Homebrew"
	/usr/bin/ruby -e "$$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	@echo "Brew already installed"
endif

.PHONY: applications
applications: brew
	brew install emacs git zsh

